# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips
spec:
  selector: # Define the wrapping strategy
    matchLabels: # Match all pods with the defined labels
      app: trips # Labels follow the `name: value` template
  template: # This is the template of the pod inside the deployment
    metadata:
      labels:
        app: trips
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - image: acrchallenge01.azurecr.io/challenge/trips
          envFrom:
            - secretRef:
                name: sql-secret-2
          name: trips
          ports:
            - containerPort: 80
              name: http
